swagger: '2.0'
info:
  title: gkeeper endpoint Cloud Endpoints + Cloud Run
  description: gkeeper api
  version: 1.0.0
host: gkeeper-gateway-wkclup33iq-an.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: 'https://gkeeper-gateway-wkclup33iq-an.a.run.app'
  protocol: h2
paths:
  '/api/list/{list_name}/item':
    post:
      summary: add item to list
      operationId: add_item
      parameters:
        - name: list_name
          in: path
          description: list name which you add item to
          required: true
          type: string
        - in: body
          name: body
          schema:
            type: object
            properties:
              item:
                type: string
          description: item which you add
      responses:
        '200':
          description: A successful response
          schema:
            type: string
        '400':
          description: Bad Request
          schema:
            type: object
            properties: {}
      description: add item to list
