name: build

on: [push]

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install poetry
        make install
    - name: Test with pytest
      run: |
        make test
    - name: GCP Authenticate
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}
    - name: build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/gkeeper:${GITHUB_SHA::7}
